resource_group_name = "rg-dev-002"
location            = "Central India"
admin_username      = "kunjanj"
admin_password      = "Whoami@123"
admin_password_name = "vm1-admin-password"
environment = "dev"